
// 
import client_avatar from "../../../../../assets/images/avatar_01.svg";
import client_avatar_1 from "../../../../../assets/images/avatar_05.svg";
import iconimg from "../../../../../assets/images/dotoption.svg";
import editiconimg from "../../../../../assets/images/editiconimg.svg";
import viewiconimg from "../../../../../assets/images/viewiconimg.svg";
import deleteiconimg from "../../../../../assets/images/deleteiconimg.svg";

import downloadiconimg from "../../../../../assets/images/download_icon.svg";
import sendiconimg from "../../../../../assets/images/sendicon.svg";
import uploadiconimg from "../../../../../assets/images/uploadfileiconblackimg.svg";
import plusiconimg from "../../../../../assets/images/plusblackicon.svg";
import linkiconimg from "../../../../../assets/images/linkiconimg.svg";
import paymenticonimg from "../../../../../assets/images/paymenticonimg.svg";

const InvoiveTableData_Array = [
    {
        key: "0",
        countnumber: "1",
        invoicenumber: "INV#040",
        projectname: "Ut assumenda quae.",
        client_avatar: client_avatar,
        client_name: "Mrs. Adele Hayes",
        total_price: "Total: $1788",
        paid_text: "Paid",
        paid_price: "$0",
        paid_color: "greencolortext",
        unpaid_text: "UnPaid",
        unpaid_price: "$1780",
        unpaid_color: "redcolortext",
        invioce_date: "11-03-2021",
        status_unpaid: "Unpaid",
        status_unpaid_bg: "badgeredbg redcolortext",
        status_notsent: "Not Sent",
        status_notsent_bg: "paragraphcolor1bg text-white",
        downloadiconimg: downloadiconimg,
        sendiconimg: sendiconimg,
        editiconimg: editiconimg,
        plusiconimg: plusiconimg,
        linkiconimg: linkiconimg,
        paymenticonimg: paymenticonimg,
        iconimg: iconimg,
        viewiconimg: viewiconimg,
        deleteiconimg: deleteiconimg,
    },
    {
        key: "1",
        countnumber: "2",
        invoicenumber: "INV#040",
        projectname: "Ut ipsam debitis.",
        client_avatar: client_avatar_1,
        client_name: "Jeremiah Shaw",
        total_price: "Total: $1788",
        paid_text: "Paid",
        paid_price: "$0",
        paid_color: "greencolortext",
        unpaid_text: "UnPaid",
        unpaid_price: "$1780",
        unpaid_color: "redcolortext",
        invioce_date: "11-03-2021",
        status_unpaid: "Paid",
        status_unpaid_bg: "badgegreenbg greencolortext",
        status_notsent: "Not Sent",
        status_notsent_bg: "paragraphcolor1bg text-white",
        downloadiconimg: downloadiconimg,
        sendiconimg: sendiconimg,
        uploadiconimg: uploadiconimg,
        plusiconimg: plusiconimg,
        editiconimg: editiconimg,
        iconimg: iconimg,
        viewiconimg: viewiconimg,
        deleteiconimg: deleteiconimg,
    },
    {
        key: "2",
        countnumber: "3",
        invoicenumber: "INV#040",
        projectname: "Ut assumenda quae.",
        client_avatar: client_avatar,
        client_name: "Mrs. Adele Hayes",
        total_price: "Total: $1788",
        paid_text: "Paid",
        paid_price: "$0",
        paid_color: "greencolortext",
        unpaid_text: "UnPaid",
        unpaid_price: "$1780",
        unpaid_color: "redcolortext",
        invioce_date: "11-03-2021",
        status_unpaid: "Unpaid",
        status_unpaid_bg: "badgeredbg redcolortext",
        status_notsent: "Not Sent",
        status_notsent_bg: "paragraphcolor1bg text-white",
        downloadiconimg: downloadiconimg,
        sendiconimg: sendiconimg,
        editiconimg: editiconimg,
        plusiconimg: plusiconimg,
        linkiconimg: linkiconimg,
        paymenticonimg: paymenticonimg,
        iconimg: iconimg,
        viewiconimg: viewiconimg,
        deleteiconimg: deleteiconimg,
    },
    {
        key: "3",
        countnumber: "4",
        invoicenumber: "INV#040",
        projectname: "Ut ipsam debitis.",
        client_avatar: client_avatar_1,
        client_name: "Jeremiah Shaw",
        total_price: "Total: $1788",
        paid_text: "Paid",
        paid_price: "$0",
        paid_color: "greencolortext",
        unpaid_text: "UnPaid",
        unpaid_price: "$1780",
        unpaid_color: "redcolortext",
        invioce_date: "11-03-2021",
        status_unpaid: "Paid",
        status_unpaid_bg: "badgegreenbg greencolortext",
        status_notsent: "Not Sent",
        status_notsent_bg: "paragraphcolor1bg text-white",
        downloadiconimg: downloadiconimg,
        sendiconimg: sendiconimg,
        uploadiconimg: uploadiconimg,
        plusiconimg: plusiconimg,
        editiconimg: editiconimg,
        iconimg: iconimg,
        viewiconimg: viewiconimg,
        deleteiconimg: deleteiconimg,
    },
]
export default InvoiveTableData_Array;