const TaskContentArray = [
    {
        key: "0",
        tdradiobtn: "radio",
        td1: "Evaluating the design",
        td2: "",
        td3: "15",
        td4: "High",
        td5: "Completed",
        classtdnth: "badgebluebg badgebluecolor",
        classtexttdnth: "badgebluecolor",
    },
    {
        key: "1",
        tdradiobtn: "radio",
        td1: "Generate ideas for design",
        td2: "",
        td3: "10",
        td4: "Normal",
        td5: "Pendig",
        classtdnth: "badgeyellowbg badgeyellowcolor",
        classtexttdnth: "badgeyellowcolor",
    },
    {
        key: "2",
        tdradiobtn: "radio",
        td1: "Define the problem",
        td2: "",
        td3: "22",
        td4: "Low",
        td5: "Completed",
        classtdnth: "badgebluebg badgebluecolor",
        classtexttdnth: "badgebluecolor",
    },
    {
        key: "3",
        tdradiobtn: "radio",
        td1: "Empathize with users",
        td2: "",
        td3: "18",
        td4: "High",
        td5: "Rejected",
        classtdnth: "badgeredbg badgeredcolor",
        classtexttdnth: "badgeredcolor",
    },
    {
        key: "4",
        tdradiobtn: "radio",
        td1: "Evaluating the design",
        td2: "",
        td3: "11",
        td4: "Normal",
        td5: "Completed",
        classtdnth: "badgebluebg badgebluecolor",
        classtexttdnth: "badgebluecolor",
    },
]

export default TaskContentArray;