// 
import avatarimg from "../../../../../assets/images/avatar_05.svg"

const Create_AttendanceLoop_Array = [
    {
        key: "0",
        title: "Brett Ratke",
        badgetext: "Backend Developer",
        badgebg: "greencolortext badgegreenbg",
        badge: "Present",
        avatarimg: avatarimg,
    },
    {
        key: "1",
        title: "Brett Ratke",
        badgetext: "Team Lead",
        badgebg: "redcolortext badgepinkbg",
        badge: "Absent",
        avatarimg: avatarimg,
        label_text_In: "Clock In",
        label_text_Out: "Clock Out",
        label_text_In_Ip: "Clock In IP",
        label_text_Out_Ip: "Clock Out IP",
        label_text_Late: "Late",
        label_text_halfday: "Half Day",
        label_text_workingfrom: "Working From",
    },
    {
        key: "2",
        title: "Brett Ratke",
        badgetext: "Team Lead",
        badgebg: "redcolortext badgepinkbg",
        badge: "Absent",
        avatarimg: avatarimg,
        label_text_In: "Clock In",
        label_text_Out: "Clock Out",
        label_text_In_Ip: "Clock In IP",
        label_text_Out_Ip: "Clock Out IP",
        label_text_Late: "Late",
        label_text_halfday: "Half Day",
        label_text_workingfrom: "Working From",
    },
    {
        key: "3",
        title: "Brett Ratke",
        badgetext: "Team Lead",
        badgebg: "redcolortext badgepinkbg",
        badge: "Absent",
        avatarimg: avatarimg,
        label_text_In: "Clock In",
        label_text_Out: "Clock Out",
        label_text_In_Ip: "Clock In IP",
        label_text_Out_Ip: "Clock Out IP",
        label_text_Late: "Late",
        label_text_halfday: "Half Day",
        label_text_workingfrom: "Working From",
    },
    {
        key: "4",
        title: "Brett Ratke",
        badgetext: "Backend Developer",
        badgebg: "greencolortext badgegreenbg",
        badge: "Present",
        avatarimg: avatarimg,
    },
]
export default Create_AttendanceLoop_Array;