// 
import avatarimg from "../../../../../assets/images/avatar_05.svg"

const ParticipationTable_Array = [
    {
        key: "0",
        title: "Brett Ratke",
        avatarimg: avatarimg,
        badgetext: "Team Lead",
        th_1: "Late",
        badgeth_1text: "No",
        th_2: "Half Day --",
        th_3: "Clock In",
        badgeth_2text: "03:30 PM",
        th_4: "Clock Out",
        badgeth_3text: "03:30 PM",
        th_5: "Other",
        clockinIP: "Clock In IP:",
        spantext1: "97.114.60.174",
        clockoutIP: "Clock out IP:",
        spantext2: "97.114.60.174",
        workingfrom: "Working From",
        spantext3: "Office",
        deletetext: "Delete",
    },
    {
        key: "1",
        title: "Brett Ratke",
        avatarimg: avatarimg,
        badgetext: "Team Lead",
        th_1: "Late",
        badgeth_1text: "No",
        th_2: "Half Day --",
        th_3: "Clock In",
        badgeth_2text: "03:30 PM",
        th_4: "Clock Out",
        badgeth_3text: "03:30 PM",
        th_5: "Other",
        clockinIP: "Clock In IP:",
        spantext1: "97.114.60.174",
        clockoutIP: "Clock out IP:",
        spantext2: "97.114.60.174",
        workingfrom: "Working From",
        spantext3: "Office",
        deletetext: "Delete",
    },
]
export default ParticipationTable_Array;