const PrecencesTable_Array = [
    {
        key: "0",
        datetext: "15-03-2021",
        badge: "Monday",
        badgecolor: "greencolortext",
        badgestatus: "Present",
        badgestatuscolor: "greencolortext",
        badgestatusbgcolor: "badgegreenbg",
        checkintext: "03:30 PM",
        checkouttext: "03:30 PM",
        clockinIP: "Clock In IP:",
        spantext1: "97.114.60.174",
        clockoutIP: "Clock out IP:",
        spantext2: "97.114.60.174",
        workingfrom: "Working From",
        spantext3: "Office",
        deletetext: "Delete",
    },
    {
        key: "1",
        datetext: "15-03-2021",
        badge: "Tuseday ",
        badgecolor: "greencolortext",
        badgestatus: "Absent",
        badgestatuscolor: "redcolortext",
        badgestatusbgcolor: "badgepinkbg",
        checkintext: "03:30 PM",
        checkouttext: "03:30 PM",
    },
    {
        key: "2",
        datetext: "15-03-2021",
        badge: "Fiday",
        badgecolor: "greencolortext",
        badgestatus: "Holiday",
        badgestatuscolor: "whitecolortext",
        badgestatusbgcolor: "blusecolorbg",
        checkintext: "03:30 PM",
        checkouttext: "03:30 PM",
        clockinIP: "Clock In IP:",
        spantext1: "97.114.60.174",
        clockoutIP: "Clock out IP:",
        spantext2: "97.114.60.174",
        workingfrom: "Working From",
        spantext3: "Office",
        deletetext: "Delete",
    },
]
export default PrecencesTable_Array;